### ISSUE TITLE
Search function when selecting plugins

### ISSUE THREAD

**Issue by Dooogurt** [matortheeternal/merge-plugins#115]
Anyway you can add a search if you're trying to combine plugins?

**Comment by matortheeternal** [comment]
You can type to search.  Just start typing the filename of the plugin you want to find and you'll jump to the plugin matching the input text buffer.  Wait long enough after a keystroke and the buffer will clear.

This feature is often requested by users who aren't merging contiguous plugins.  If you find yourself wanting to have a search, it probably means you're using the program incorrectly.
