### ISSUE TITLE
Masters not removed when using German Language

### ISSUE THREAD

**Issue by matortheeternal** [matortheeternal/merge-plugins#122]
Related to translation of renumbering/copying methods?  Not sure.

**Comment by MrEbonycat** [comment]
The same problem when using Chinese Language with Merge Plugins v2.2.3 .
When I changed 
`mpEdit_cbMethod_Item0=覆盖
mpEdit_cbMethod_Item1=新记录
mpEdit_lblRenumbering_Caption=重编号
mpEdit_cbRenumbering_Item0=冲突项
mpEdit_cbRenumbering_Item1=所有` 
to 
`mpEdit_cbMethod_Item0=Overrides
mpEdit_cbMethod_Item1=New records
mpEdit_lblRenumbering_Caption=重编号
mpEdit_cbRenumbering_Item0=Conflicting
mpEdit_cbRenumbering_Item1=All` 
in  "...\lang\chinese.lang",
masters has been removed successfully.

**Comment by MrEbonycat** [comment]
There are the screenshots.
Before:
<img src="http://i3.imgbus.com/doimg/b4530974f1588489b8.JPG" />
After:
<img src="http://i4.imgbus.com/doimg/b45339a74a15183591.JPG" />

**Comment by lentil1016** [comment]
Issue remain in 2.3.1.0, shall we release a new version? It's been like a year since the last release.
