### ISSUE TITLE
Possible superfluous setting.

### ISSUE THREAD

**Issue by GrantSP** [matortheeternal/merge-plugins#123]
On the **Merging** tab of the _Settings_ dialogue there is a field to set the "Merge destination path".
Then on the **Integrations** tab of the _Settings_ dialogue there is also a field to set the "Mod manager mods path".

Since those two paths should be pointing to the same location, at least that is the assumption I'm making, isn't only one of them necessary? It is possible, as I found out, to incorrectly set one and the resultant merge was not found in the **mods** folder I was expecting. Possibly this only shows because I have set both my **downloads** & **mods** folders to a different drive to that of the MO executable.

**Comment by matortheeternal** [comment]
When using NMM the two paths need to be different.  It's important to have the distinction for other reasons as well.
