### ISSUE TITLE
[Fallout 4] Update for DLC ESM

### ISSUE THREAD

**Issue by InsanePlumber** [matortheeternal/merge-plugins#128]
I hope that this will be useful.

`DLCRobot.esm;50532;2.2;-1.0;1;[User: InsanePlumber] [Hash: D69027EA] [Version: 2.2.1.1]@13Can't merge Bethesda files.@13@13`

`DLCworkshop01.esm;1528;2.2;-1.0;1;[User: InsanePlumber] [Hash: 47BAE27E] [Version: 2.2.1.1]@13Can't merge Bethesda files.@13@13`

`DLCCoast.esm;320320;2.2;-1.0;1;[User: InsanePlumber] [Hash: F1F20826] [Version: 2.2.1.1]@13Can't merge Bethesda files.@13@13`

`DLCworkshop02.esm;1759;2.2;-1.0;1;[User: InsanePlumber] [Hash: 83ABC821] [Version: 2.2.1.1]@13Can't merge Bethesda files.@13@13`

`DLCworkshop03.esm;12749;2.2;-1.0;1;[User: InsanePlumber] [Hash: E0089FBB] [Version: 2.2.1.1]@13Can't merge Bethesda files.@13@13`

`DLCNukaWorld.esm;282869;2.2;-1.0;1;[User: InsanePlumber] [Hash: 97884152] [Version: 2.2.1.1]@13Can't merge Bethesda files.@13@13`

**Comment by matortheeternal** [comment]
Thanks, but you should submit these through the client so I can get them into the backend database properly.  :+1:
