### ISSUE TITLE
Record merging fails with "Duplicate FormID" on CELL records

### ISSUE THREAD

**Issue by tricus** [matortheeternal/merge-plugins#30]
After a number of other successful merges I've encountered errors attempting to merge two plugins of a particular Fallout New Vegas mod:
&nbsp;&nbsp;NVInteriors Core: http://www.nexusmods.com/newvegas/download/1000014216 
and
&nbsp;&nbsp;NVInteriors Combo AWOP: http://www.nexusmods.com/newvegas/download/110976 

Log contents here:  http://pastebin.com/FTsNQ0iw

I had to snip part of the log to fit in the 512kb limit but the errors are all of the same type, "Duplicate FormID", as shown here:

> Exception copying [REFR:0C000B47] (places StreetLitterDark02 [STAT:000401D2] in GRUP Cell Temporary Children of NVInteriorsSouthSewers "South Sewers" [CELL:0C0F7FE6]): Duplicate FormID [020F7FE6] in file [0E] MERGE - NVInteriors Core w-ComboEdition_AWOP.esm

The merge completes with 3347 such errors, and the resulting plugin has 3425 less records than expected (assuming sum of records from both mods).

The only other things in the load order are the core game files and DLCs.  I also tried without the DLCs present, with the same result.

I don't know if the FormID starting with "02" is a clue.  The "02" mod prefix doesn't correspond to a mod that is involved in the merge but perhaps the formid renumbering is a normal artifact of the merging process..

The only difference I have noticed between these mods and others that have successfully merged is that NVInteriors Combo AWOP has 455 ONAM records, but I don't know if this is relevant.

Please let me know if I can provide any more information.

**Comment by InsanePlumber** [comment]
Both plug-ins contain errors.

NVInteriors_Core.esm

[00:00] Checking for Errors in [01] NVInteriors_Core.esm
[00:00] FNVIntIrradatedCandyBar01 "Irradiated Candy Bar" [ALCH:0102B7BF]
[00:00]     ALCH \ Effects \ Effect \ Conditions \ CTDA - Condition \ Parameter #1 -> Found a NULL reference, expected: ALCH,AMMO,ARMO,BOOK,CHIP,CMNY,FLST,IMOD,KEYM,MISC,NOTE,WEAP
[00:00] FNVIntIrradatedBBQSauce01Full "Irr. Flamin' Hot, BBQ Sauce" [ALCH:0102B4EA]
[00:00]     ALCH \ Effects \ Effect \ Conditions \ CTDA - Condition \ Parameter #1 -> Found a NULL reference, expected: ALCH,AMMO,ARMO,BOOK,CHIP,CMNY,FLST,IMOD,KEYM,MISC,NOTE,WEAP
[00:00] All Done!

---

NVInteriors_ComboEdition_AWOP.esm

[00:00] Checking for Errors in [02] NVInteriors_ComboEdition_AWOP.esm
[00:00] FNVIntFreesideHomeTemp02 [SCOL:02001442]
[00:00]     SCOL \ Parts \ Part \ ONAM - Static -> Found a NULL reference, expected: STAT
[00:00] FNVIntFreesideHomeTemp02a [SCOL:020F82BA]
[00:00]     SCOL \ Parts \ Part \ ONAM - Static -> Found a NULL reference, expected: STAT
[00:06] All Done!

---
- Remove errors from plug-ins
- Convert NVInteriors_ComboEdition_AWOP.esm in to ESP
- Load NVInteriors_ComboEdition_AWOP.esp in GECK, after load in GECK !!ONLY SAVE!!
- Now Merge NVInteriors_ComboEdition_AWOP.esm and NVInteriors_ComboEdition_AWOP.esp
- Convert merged file to ESM

---

Building merge: NVInteriorsComboEditionAWOP

Merge is using plugin: NVInteriorsComboEditionAWOP.esp
Merge data path: F:\install\steam\SteamApps\common\Fallout New Vegas enplczru\NewMerge\
Adding masters...
Done adding masters

Renumbering Conflicting FormIDs
  Renumbering FormIDs in NVInteriors_Core.esm
  Renumbering FormIDs in NVInteriors_ComboEdition_AWOP.esp

Copying records
  Copying records from NVInteriors_ComboEdition_AWOP.esp
  Copying records from NVInteriors_Core.esm

Handling assets
  Handling assets for NVInteriors_ComboEdition_AWOP.esp
  Handling assets for NVInteriors_Core.esm

Removing unncessary masters
  Removing master NVInteriors_ComboEdition_AWOP.esp
  Removing master NVInteriors_Core.esm

Discarding changes to source plugins
  Reloading NVInteriors_Core.esm from disk
  Reloading NVInteriors_ComboEdition_AWOP.esp from disk

Saving: F:\install\steam\SteamApps\common\Fallout New Vegas enplczru\NVInteriorsComboEditionAWOP\NVInteriorsComboEditionAWOP.esp
Done merging NVInteriorsComboEditionAWOP (61.838s)
 All done!

---

[00:00] Checking for Errors in [01] NVInteriorsComboEditionAWOP.esp
[00:07] All Done!

**Comment by matortheeternal** [comment]
Invalid per InsanePlumber.
