### ISSUE TITLE
Implement sorting by Plugins tab columns

### ISSUE THREAD

**Issue by erlunsford** [matortheeternal/merge-plugins#74]
Being able to sort by the Index, Filename, and Merge columns would be a great enhancement

**Comment by matortheeternal** [comment]
No, I'm not doing this.  I have specific reasons why I don't want to do this that I've outlined before.  If people feel the need to sort the plugins list then they're merging plugins incorrectly.  The plugins they want to merge should be contiguous in their load order.  If the plugins are contiguous, then there's no need for sorting.

**Comment by erlunsford** [comment]
Got it, sorry, I just this moment read your reasoning in another forum somewhere.

**Comment by matortheeternal** [comment]
Sure thing, no problem.  :+1:
