### ISSUE TITLE
Masters and Depencies Plugin Selection Popup Menu Items

### ISSUE THREAD

**Issue by erlunsford** [matortheeternal/merge-plugins#75]
The addition of the Plugin Selection dialog was a wonderful enhancment!

What I find myself doing, since I have so many mods, is unselecting everything, then selecting all the Merged esps and their masters.

If there could be an easy way to do that, it would be perfect.

**Comment by matortheeternal** [comment]
New popup menu items:
- ~~Masters~~
  - ~~Check masters~~
  - ~~Uncheck masters~~
- ~~Dependencies~~
  - ~~Check dependent plugins~~
  - ~~Uncheck dependent plugins~~
- Merges
  - Uncheck plugins in merge (when right-clicking a merge)
  - Check plugins in merge (when right-clicking a merge)
  - Check all plugins in merges
  - Uncheck all merged plugins

The only issue with this is it requires adding merge-specific functionality to the popup menu (for the merges group of options) which should ideally be kept decoupled from this form so the form can be reused.  (The form is currently completely decoupled from the functionality of Merge Plugins so it can be reused freely).  Keeping the form decoupled could be difficult when adding the merge-specific options.

**Comment by matortheeternal** [comment]
In d4bdf59 I added the Masters and Dependencies submenus.

**Comment by matortheeternal** [comment]
In regards to decoupling, the only thing I can imagine doing is extending the plugin selection form by making a new form which inherits from it.  I can't just pass the menu items and their OnClick events, because their events need to interface with the Plugins List View on the Plugin Selection Window.

**Comment by erlunsford** [comment]
Just having the "Check dependents" is a big improvement. As you've mentioned (and I try to follow), plugins in a merge should be contiguous, so they're not bad, but hunting down all their dependencies was more of a chore. Thanks for the quick update!

**Comment by matortheeternal** [comment]
@erlunsford I'm glad it made a difference for you!  :+1:

**Comment by matortheeternal** [comment]
Creating a new issue for the merges popup menu items.  #87
