### ISSUE TITLE
Merge logs/batch files not cleared when rebuilding a merge

### ISSUE THREAD

**Issue by erlunsford** [matortheeternal/merge-plugins#76]
This is a small, but annoying issue. 

If I have a merge that includes scripts, the merge will create "XXX-CompileLog.txt", "XXX-Compile.bat", etc. files (which is good!)

Now, if I remove the only esp that had the scripts and rebuild the merge, the old CompileLog.txt, etc., files remain, which can be confusing. I can just get in the habit of deleting the contents of the Mod Organizer mod folder "XXX" before rebuilding, I know, but thought this might be a good suggestion.

**Comment by matortheeternal** [comment]
That's a bug, will fix.
