### ISSUE TITLE
Unable to rebuild after mod removal

### ISSUE THREAD

**Issue by erlunsford** [matortheeternal/merge-plugins#77]
If I build a merge, then remove one of the esps from the merge and want to rebuild, there's no way to do it. That is to say, the merge on the Merges tab still shows as up-to-date (bold, black) and both the Rebuild Merge and Toggle Rebuild Status items on the context menu are disabled.

**Comment by matortheeternal** [comment]
Bold, black is the "Built" merge status.  A merge that has been built cannot be rebuilt in the same session of the program due to limitations in the xEdit API.  Not being able to rebuild it is actually an intentional protection.

**Comment by erlunsford** [comment]
OK, understood, makes sense.
